/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import POJO.Consulta;
import POJO.DadosAdicionais;
import POJO.Paciente;
import POJO.Prontuario;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sistema.GerenciadorMsg;
import sistema.Medico;

/**
 *
 * @author aleix
 */
public class UIGerenciadorMsg extends javax.swing.JFrame {

    final CardLayout menu;
    final CardLayout opcoesGerenciadorMsg;
    final DateTimeFormatter toBarras;
    private List<Paciente> pacientes;
    private List<Consulta> consultas;

    GerenciadorMsg ctrlMsg;
    
    public UIGerenciadorMsg() {
        initComponents();
        menu = (CardLayout) (cardMenu.getLayout());
        opcoesGerenciadorMsg = (CardLayout) (cardOpcoesGerenciador.getLayout());
        opcoesGerenciadorMsg.show(cardOpcoesGerenciador, "telaDefault");
        this.toBarras = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        this.ctrlMsg = new GerenciadorMsg();
        setSize(new Dimension(804, 600));
    }
    
    public UIGerenciadorMsg(ArrayList<Paciente> pacientes, ArrayList<Consulta> consultas) {
        initComponents();
        menu = (CardLayout) (cardMenu.getLayout());
        this.toBarras = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        opcoesGerenciadorMsg = (CardLayout) (cardOpcoesGerenciador.getLayout());
        opcoesGerenciadorMsg.show(cardOpcoesGerenciador, "telaDefault");
        this.pacientes = pacientes;
        this.consultas = consultas;
        this.ctrlMsg = new GerenciadorMsg();
        setSize(new Dimension(804, 600));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        cardMenu = new javax.swing.JPanel();
        menuGerenciadorMsg = new javax.swing.JPanel();
        botaoVoltarMain = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        botaoGerengiarMsg = new javax.swing.JButton();
        cardOpcoesGerenciador = new javax.swing.JPanel();
        telaDefault = new javax.swing.JPanel();
        telaGerenciarMsg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPacientes = new javax.swing.JList<>();
        painelEnviarMsg = new javax.swing.JPanel();
        botaoEnviarMsgTodos = new javax.swing.JButton();
        botaoEnviarMsg = new javax.swing.JButton();
        painelConsProxDia = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        consProximoDiaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cardMenu.setPreferredSize(new java.awt.Dimension(226, 536));
        cardMenu.setLayout(new java.awt.CardLayout());

        menuGerenciadorMsg.setBackground(new java.awt.Color(204, 204, 204));

        botaoVoltarMain.setBackground(new java.awt.Color(204, 204, 204));
        botaoVoltarMain.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoVoltarMain.setForeground(new java.awt.Color(51, 51, 51));
        botaoVoltarMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoVoltarMain.setText("Voltar");
        botaoVoltarMain.setBorder(null);
        botaoVoltarMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVoltarMain.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoVoltarMain.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoVoltarMain.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoVoltarMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarMainvoltarMenuPrincipal(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/back.png"))); // NOI18N

        botaoGerengiarMsg.setBackground(new java.awt.Color(204, 204, 204));
        botaoGerengiarMsg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoGerengiarMsg.setForeground(new java.awt.Color(51, 51, 51));
        botaoGerengiarMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoGerengiarMsg.setText("Gerenciar Mensagens");
        botaoGerengiarMsg.setBorder(null);
        botaoGerengiarMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoGerengiarMsg.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoGerengiarMsg.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoGerengiarMsg.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoGerengiarMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGerengiarMsgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuGerenciadorMsgLayout = new javax.swing.GroupLayout(menuGerenciadorMsg);
        menuGerenciadorMsg.setLayout(menuGerenciadorMsgLayout);
        menuGerenciadorMsgLayout.setHorizontalGroup(
            menuGerenciadorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuGerenciadorMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuGerenciadorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuGerenciadorMsgLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoGerengiarMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuGerenciadorMsgLayout.setVerticalGroup(
            menuGerenciadorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuGerenciadorMsgLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(botaoGerengiarMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                .addGap(402, 402, 402)
                .addGroup(menuGerenciadorMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoVoltarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(16, 16, 16))
        );

        cardMenu.add(menuGerenciadorMsg, "menuGerenciadorMsg");

        jSplitPane1.setLeftComponent(cardMenu);

        cardOpcoesGerenciador.setMaximumSize(new java.awt.Dimension(1000, 1000));
        cardOpcoesGerenciador.setMinimumSize(new java.awt.Dimension(804, 582));
        cardOpcoesGerenciador.setLayout(new java.awt.CardLayout());

        telaDefault.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout telaDefaultLayout = new javax.swing.GroupLayout(telaDefault);
        telaDefault.setLayout(telaDefaultLayout);
        telaDefaultLayout.setHorizontalGroup(
            telaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        telaDefaultLayout.setVerticalGroup(
            telaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        cardOpcoesGerenciador.add(telaDefault, "telaDefault");

        telaGerenciarMsg.setBackground(new java.awt.Color(51, 51, 51));

        jScrollPane1.setViewportView(listaPacientes);

        painelEnviarMsg.setBackground(new java.awt.Color(51, 51, 51));

        botaoEnviarMsgTodos.setBackground(new java.awt.Color(204, 204, 204));
        botaoEnviarMsgTodos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoEnviarMsgTodos.setForeground(new java.awt.Color(51, 51, 51));
        botaoEnviarMsgTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoEnviarMsgTodos.setText("Enviar mensagem para todos os pacientes");
        botaoEnviarMsgTodos.setBorder(null);
        botaoEnviarMsgTodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoEnviarMsgTodos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoEnviarMsgTodos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoEnviarMsgTodos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoEnviarMsgTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarMsgTodosActionPerformed(evt);
            }
        });

        botaoEnviarMsg.setBackground(new java.awt.Color(204, 204, 204));
        botaoEnviarMsg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoEnviarMsg.setForeground(new java.awt.Color(51, 51, 51));
        botaoEnviarMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoEnviarMsg.setText("Enviar Mensagem");
        botaoEnviarMsg.setBorder(null);
        botaoEnviarMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoEnviarMsg.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoEnviarMsg.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoEnviarMsg.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoEnviarMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarMsgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelEnviarMsgLayout = new javax.swing.GroupLayout(painelEnviarMsg);
        painelEnviarMsg.setLayout(painelEnviarMsgLayout);
        painelEnviarMsgLayout.setHorizontalGroup(
            painelEnviarMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnviarMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoEnviarMsgTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoEnviarMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelEnviarMsgLayout.setVerticalGroup(
            painelEnviarMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnviarMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEnviarMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEnviarMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoEnviarMsgTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelConsProxDia.setBackground(new java.awt.Color(51, 51, 51));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Os seguintes pacientes possuem consulta cadastrada para o dia");

        consProximoDiaField.setEditable(false);
        consProximoDiaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consProximoDiaFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelConsProxDiaLayout = new javax.swing.GroupLayout(painelConsProxDia);
        painelConsProxDia.setLayout(painelConsProxDiaLayout);
        painelConsProxDiaLayout.setHorizontalGroup(
            painelConsProxDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsProxDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consProximoDiaField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelConsProxDiaLayout.setVerticalGroup(
            painelConsProxDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConsProxDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConsProxDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(consProximoDiaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout telaGerenciarMsgLayout = new javax.swing.GroupLayout(telaGerenciarMsg);
        telaGerenciarMsg.setLayout(telaGerenciarMsgLayout);
        telaGerenciarMsgLayout.setHorizontalGroup(
            telaGerenciarMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaGerenciarMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaGerenciarMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addComponent(painelConsProxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelEnviarMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(417, 417, 417))
        );
        telaGerenciarMsgLayout.setVerticalGroup(
            telaGerenciarMsgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaGerenciarMsgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelConsProxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(painelEnviarMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardOpcoesGerenciador.add(telaGerenciarMsg, "telaGerenciarMsg");

        jSplitPane1.setRightComponent(cardOpcoesGerenciador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarMainvoltarMenuPrincipal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarMainvoltarMenuPrincipal
        // TODO add your handling code here:
        this.setVisible(false);
        new trabalho2.Trabalho2().show();
    }//GEN-LAST:event_botaoVoltarMainvoltarMenuPrincipal
    
        public void atualizarListaGerenciadorMsg(){
        if (consultas.isEmpty()) {
            opcoesGerenciadorMsg.show(cardOpcoesGerenciador, "telaDefault");
            JOptionPane.showMessageDialog(null, "Nenhuma consulta cadastrada", "Gerenciar Mensagens", JOptionPane.WARNING_MESSAGE);
        }else{
             DefaultListModel relConsultas = new DefaultListModel();
             consultas.forEach(itens -> {
                 relConsultas.addElement(itens.getPaciente().getNome());
            });
             listaPacientes.setModel(relConsultas);
        }
    }
    
    public void removerPacSemCons(){
       for (int i = 0; i < consultas.size(); i++) {
            if (!consultas.get(i).getLocalDateCons().equals(LocalDate.now().plusDays(1))) {
                consultas.remove(i);
                i--;
            }
        }
    }
    private void botaoGerengiarMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGerengiarMsgActionPerformed
        // TODO add your handling code here:
        opcoesGerenciadorMsg.show(cardOpcoesGerenciador, "telaGerenciarMsg");
        consultas = ctrlMsg.consultarConsultas();
        consProximoDiaField.setText(LocalDate.now().plusDays(1).format(toBarras));        
        removerPacSemCons();
        atualizarListaGerenciadorMsg();
        
    }//GEN-LAST:event_botaoGerengiarMsgActionPerformed

    private void botaoEnviarMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarMsgActionPerformed

        int horario = consultas.get(listaPacientes.getSelectedIndex()).getHorario();
        int telefone = consultas.get(listaPacientes.getSelectedIndex()).getPaciente().getTelefone();
        String email = consultas.get(listaPacientes.getSelectedIndex()).getPaciente().getEmail();

        ctrlMsg.enviarMensagem(horario, telefone, email);

    }//GEN-LAST:event_botaoEnviarMsgActionPerformed

    private void botaoEnviarMsgTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarMsgTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEnviarMsgTodosActionPerformed

    private void consProximoDiaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consProximoDiaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consProximoDiaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIGerenciadorMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIGerenciadorMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIGerenciadorMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIGerenciadorMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIGerenciadorMsg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviarMsg;
    private javax.swing.JButton botaoEnviarMsgTodos;
    private javax.swing.JButton botaoGerengiarMsg;
    private javax.swing.JButton botaoVoltarMain;
    private javax.swing.JPanel cardMenu;
    private javax.swing.JPanel cardOpcoesGerenciador;
    private javax.swing.JTextField consProximoDiaField;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList<String> listaPacientes;
    private javax.swing.JPanel menuGerenciadorMsg;
    private javax.swing.JPanel painelConsProxDia;
    private javax.swing.JPanel painelEnviarMsg;
    private javax.swing.JPanel telaDefault;
    private javax.swing.JPanel telaGerenciarMsg;
    // End of variables declaration//GEN-END:variables
}
