/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import POJO.Consulta;
import POJO.Paciente;
import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.ResourceBundle.Control;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JSplitPane;
import javax.swing.JTextField;
import sistema.Secretaria;
/**
 *
 * @author aleix
 */
public class UISecretaria extends javax.swing.JFrame {
    final CardLayout menu;
    final CardLayout opcoesSec;
    final DateTimeFormatter toBarras; 

    final ArrayList<Paciente> pacientes;
    final ArrayList<Consulta> consultas; 

    /**
     * Creates new form secretaria
     */
    public UISecretaria() {
        initComponents();
        menu = (CardLayout) (cardMenu.getLayout());
        opcoesSec = (CardLayout) (cardOpcoesSecretaria.getLayout());
        opcoesSec.show(cardOpcoesSecretaria, "telaDefault");
        this.toBarras = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        this.pacientes = new ArrayList<>();
        this.consultas = new ArrayList<>();
    }
    
    public UISecretaria(ArrayList<Paciente> pacientes, ArrayList<Consulta> consultas) {
        initComponents();
        menu = (CardLayout) (cardMenu.getLayout());
        this.toBarras = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        opcoesSec = (CardLayout) (cardOpcoesSecretaria.getLayout());
        opcoesSec.show(cardOpcoesSecretaria, "telaDefault");
        this.pacientes = pacientes;
        this.consultas = consultas;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoConvenio = new javax.swing.ButtonGroup();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSplitPane2 = new javax.swing.JSplitPane();
        cardMenu = new javax.swing.JPanel();
        menuSecretaria = new javax.swing.JPanel();
        botaoVoltarMain = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        botaoRelatorio = new javax.swing.JButton();
        botaoPaciente = new javax.swing.JButton();
        botaoConsulta = new javax.swing.JButton();
        menuGerenciarPaciente = new javax.swing.JPanel();
        botaoVoltarSec = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        botaoRemover = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        cardOpcoesSecretaria = new javax.swing.JPanel();
        atualizarPaciente = new javax.swing.JPanel();
        painelSelecionarPaciente = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pacientesBox = new javax.swing.JComboBox<>();
        painelAtualizaCidade = new javax.swing.JPanel();
        atualizaCidadeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        painelAtualizaBairro = new javax.swing.JPanel();
        atualizaBairroField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        painelAtualizaNome = new javax.swing.JPanel();
        atualizaNomeField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        painelAtualizaRua = new javax.swing.JPanel();
        atualizaRuaField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        painelAtualizaTelefone = new javax.swing.JPanel();
        atualizaTelField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        painelAtualizaData = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        atualizaDataNascCalendar = new com.toedter.calendar.JDateChooser();
        painelAtualizaConvenio = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        atualizaRadioParticular = new javax.swing.JRadioButton();
        atualizaRadioPlanodeSaude = new javax.swing.JRadioButton();
        removerPaciente = new javax.swing.JPanel();
        telaDefault = new javax.swing.JPanel();
        cadastrarPaciente = new javax.swing.JPanel();
        painelCidade = new javax.swing.JPanel();
        cidadeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        painelBairro = new javax.swing.JPanel();
        bairroField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        painelNome = new javax.swing.JPanel();
        nomeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        painelRua = new javax.swing.JPanel();
        ruaField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        painelTelefone = new javax.swing.JPanel();
        telField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        painelData = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        dataNascCalendar = new com.toedter.calendar.JDateChooser();
        painelConvenio = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        radioParticular = new javax.swing.JRadioButton();
        radioPlanodeSaude = new javax.swing.JRadioButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        painelSalvar = new javax.swing.JPanel();
        botaoSalvarDados = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cardMenu.setPreferredSize(new java.awt.Dimension(226, 536));
        cardMenu.setLayout(new java.awt.CardLayout());

        menuSecretaria.setBackground(new java.awt.Color(204, 204, 204));

        botaoVoltarMain.setBackground(new java.awt.Color(204, 204, 204));
        botaoVoltarMain.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoVoltarMain.setForeground(new java.awt.Color(51, 51, 51));
        botaoVoltarMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoVoltarMain.setText("Voltar");
        botaoVoltarMain.setBorder(null);
        botaoVoltarMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVoltarMain.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoVoltarMain.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoVoltarMain.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoVoltarMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarMainvoltarMenuPrincipal(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/back.png"))); // NOI18N

        botaoRelatorio.setBackground(new java.awt.Color(204, 204, 204));
        botaoRelatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoRelatorio.setForeground(new java.awt.Color(51, 51, 51));
        botaoRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoRelatorio.setText("Emitir Relatórios");
        botaoRelatorio.setBorder(null);
        botaoRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoRelatorio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoRelatorio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoRelatorio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatorioActionPerformed(evt);
            }
        });

        botaoPaciente.setBackground(new java.awt.Color(204, 204, 204));
        botaoPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoPaciente.setForeground(new java.awt.Color(51, 51, 51));
        botaoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoPaciente.setText("Gerenciar Paciente");
        botaoPaciente.setBorder(null);
        botaoPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoPaciente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoPaciente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoPaciente.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPacienteActionPerformed(evt);
            }
        });

        botaoConsulta.setBackground(new java.awt.Color(204, 204, 204));
        botaoConsulta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoConsulta.setForeground(new java.awt.Color(51, 51, 51));
        botaoConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoConsulta.setText("Gerenciar Consulta");
        botaoConsulta.setBorder(null);
        botaoConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoConsulta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoConsulta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoConsulta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N

        javax.swing.GroupLayout menuSecretariaLayout = new javax.swing.GroupLayout(menuSecretaria);
        menuSecretaria.setLayout(menuSecretariaLayout);
        menuSecretariaLayout.setHorizontalGroup(
            menuSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSecretariaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuSecretariaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(menuSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuSecretariaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(botaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        menuSecretariaLayout.setVerticalGroup(
            menuSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuSecretariaLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(botaoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                .addGap(154, 154, 154)
                .addComponent(botaoRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                .addGap(189, 189, 189)
                .addGroup(menuSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoVoltarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(25, 25, 25))
            .addGroup(menuSecretariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuSecretariaLayout.createSequentialGroup()
                    .addGap(185, 185, 185)
                    .addComponent(botaoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                    .addGap(339, 339, 339)))
        );

        cardMenu.add(menuSecretaria, "menuSecretaria");

        menuGerenciarPaciente.setBackground(new java.awt.Color(204, 204, 204));

        botaoVoltarSec.setBackground(new java.awt.Color(204, 204, 204));
        botaoVoltarSec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoVoltarSec.setForeground(new java.awt.Color(51, 51, 51));
        botaoVoltarSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoVoltarSec.setText("Voltar");
        botaoVoltarSec.setBorder(null);
        botaoVoltarSec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVoltarSec.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoVoltarSec.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoVoltarSec.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoVoltarSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarSecvoltarMenuPrincipal(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icones/back.png"))); // NOI18N

        botaoRemover.setBackground(new java.awt.Color(204, 204, 204));
        botaoRemover.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoRemover.setForeground(new java.awt.Color(51, 51, 51));
        botaoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoRemover.setText("Remover Paciente");
        botaoRemover.setBorder(null);
        botaoRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoRemover.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoRemover.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoRemover.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        botaoAtualizar.setBackground(new java.awt.Color(204, 204, 204));
        botaoAtualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoAtualizar.setForeground(new java.awt.Color(51, 51, 51));
        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoAtualizar.setText("Atualizar Paciente");
        botaoAtualizar.setBorder(null);
        botaoAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoAtualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoAtualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoAtualizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        botaoCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(51, 51, 51));
        botaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoCadastrar.setText("Cadastrar Paciente");
        botaoCadastrar.setBorder(null);
        botaoCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoCadastrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoCadastrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoCadastrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuGerenciarPacienteLayout = new javax.swing.GroupLayout(menuGerenciarPaciente);
        menuGerenciarPaciente.setLayout(menuGerenciarPacienteLayout);
        menuGerenciarPacienteLayout.setHorizontalGroup(
            menuGerenciarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuGerenciarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuGerenciarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuGerenciarPacienteLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoVoltarSec, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuGerenciarPacienteLayout.setVerticalGroup(
            menuGerenciarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuGerenciarPacienteLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 46, Short.MAX_VALUE)
                .addGap(189, 189, 189)
                .addGroup(menuGerenciarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoVoltarSec, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25))
        );

        cardMenu.add(menuGerenciarPaciente, "menuGerenciarPaciente");

        jSplitPane2.setLeftComponent(cardMenu);

        cardOpcoesSecretaria.setLayout(new java.awt.CardLayout());

        atualizarPaciente.setBackground(new java.awt.Color(51, 51, 51));

        painelSelecionarPaciente.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Selecione o paciente");

        pacientesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout painelSelecionarPacienteLayout = new javax.swing.GroupLayout(painelSelecionarPaciente);
        painelSelecionarPaciente.setLayout(painelSelecionarPacienteLayout);
        painelSelecionarPacienteLayout.setHorizontalGroup(
            painelSelecionarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSelecionarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pacientesBox, 0, 123, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelSelecionarPacienteLayout.setVerticalGroup(
            painelSelecionarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSelecionarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSelecionarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pacientesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        painelAtualizaCidade.setBackground(new java.awt.Color(51, 51, 51));

        atualizaCidadeField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Cidade");

        javax.swing.GroupLayout painelAtualizaCidadeLayout = new javax.swing.GroupLayout(painelAtualizaCidade);
        painelAtualizaCidade.setLayout(painelAtualizaCidadeLayout);
        painelAtualizaCidadeLayout.setHorizontalGroup(
            painelAtualizaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizaCidadeField)
                    .addGroup(painelAtualizaCidadeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelAtualizaCidadeLayout.setVerticalGroup(
            painelAtualizaCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizaCidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizaBairro.setBackground(new java.awt.Color(51, 51, 51));

        atualizaBairroField.setBackground(new java.awt.Color(255, 255, 255));
        atualizaBairroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaBairroFieldActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Bairro");

        javax.swing.GroupLayout painelAtualizaBairroLayout = new javax.swing.GroupLayout(painelAtualizaBairro);
        painelAtualizaBairro.setLayout(painelAtualizaBairroLayout);
        painelAtualizaBairroLayout.setHorizontalGroup(
            painelAtualizaBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaBairroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizaBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizaBairroField, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGroup(painelAtualizaBairroLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelAtualizaBairroLayout.setVerticalGroup(
            painelAtualizaBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaBairroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizaBairroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizaNome.setBackground(new java.awt.Color(51, 51, 51));

        atualizaNomeField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Nome");

        javax.swing.GroupLayout painelAtualizaNomeLayout = new javax.swing.GroupLayout(painelAtualizaNome);
        painelAtualizaNome.setLayout(painelAtualizaNomeLayout);
        painelAtualizaNomeLayout.setHorizontalGroup(
            painelAtualizaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizaNomeField)
                    .addGroup(painelAtualizaNomeLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelAtualizaNomeLayout.setVerticalGroup(
            painelAtualizaNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizaNomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizaRua.setBackground(new java.awt.Color(51, 51, 51));

        atualizaRuaField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Rua");

        javax.swing.GroupLayout painelAtualizaRuaLayout = new javax.swing.GroupLayout(painelAtualizaRua);
        painelAtualizaRua.setLayout(painelAtualizaRuaLayout);
        painelAtualizaRuaLayout.setHorizontalGroup(
            painelAtualizaRuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaRuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizaRuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atualizaRuaField)
                    .addGroup(painelAtualizaRuaLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelAtualizaRuaLayout.setVerticalGroup(
            painelAtualizaRuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaRuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizaRuaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizaTelefone.setBackground(new java.awt.Color(51, 51, 51));

        atualizaTelField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Telefone");

        javax.swing.GroupLayout painelAtualizaTelefoneLayout = new javax.swing.GroupLayout(painelAtualizaTelefone);
        painelAtualizaTelefone.setLayout(painelAtualizaTelefoneLayout);
        painelAtualizaTelefoneLayout.setHorizontalGroup(
            painelAtualizaTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizaTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAtualizaTelefoneLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(atualizaTelField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
        );
        painelAtualizaTelefoneLayout.setVerticalGroup(
            painelAtualizaTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizaTelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizaData.setBackground(new java.awt.Color(51, 51, 51));

        jLabel16.setBackground(new java.awt.Color(204, 204, 204));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Data de Nascimento");

        atualizaDataNascCalendar.setBackground(new java.awt.Color(255, 255, 255));
        atualizaDataNascCalendar.setDateFormatString("dd-MM-yyyy");
        atualizaDataNascCalendar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout painelAtualizaDataLayout = new javax.swing.GroupLayout(painelAtualizaData);
        painelAtualizaData.setLayout(painelAtualizaDataLayout);
        painelAtualizaDataLayout.setHorizontalGroup(
            painelAtualizaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(151, 151, 151))
            .addGroup(painelAtualizaDataLayout.createSequentialGroup()
                .addComponent(atualizaDataNascCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelAtualizaDataLayout.setVerticalGroup(
            painelAtualizaDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizaDataNascCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAtualizaConvenio.setBackground(new java.awt.Color(51, 51, 51));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Tipo de Convênio");

        atualizaRadioParticular.setBackground(new java.awt.Color(51, 51, 51));
        grupoConvenio.add(atualizaRadioParticular);
        atualizaRadioParticular.setForeground(new java.awt.Color(204, 204, 204));
        atualizaRadioParticular.setText("Particular");
        atualizaRadioParticular.setActionCommand("particular");
        atualizaRadioParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizaRadioParticularActionPerformed(evt);
            }
        });

        atualizaRadioPlanodeSaude.setBackground(new java.awt.Color(51, 51, 51));
        grupoConvenio.add(atualizaRadioPlanodeSaude);
        atualizaRadioPlanodeSaude.setForeground(new java.awt.Color(204, 204, 204));
        atualizaRadioPlanodeSaude.setText("Plano de Saúde");
        atualizaRadioPlanodeSaude.setActionCommand("plano de saúde");

        javax.swing.GroupLayout painelAtualizaConvenioLayout = new javax.swing.GroupLayout(painelAtualizaConvenio);
        painelAtualizaConvenio.setLayout(painelAtualizaConvenioLayout);
        painelAtualizaConvenioLayout.setHorizontalGroup(
            painelAtualizaConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaConvenioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAtualizaConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelAtualizaConvenioLayout.createSequentialGroup()
                        .addComponent(atualizaRadioParticular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(atualizaRadioPlanodeSaude)))
                .addContainerGap())
        );
        painelAtualizaConvenioLayout.setVerticalGroup(
            painelAtualizaConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAtualizaConvenioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(painelAtualizaConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizaRadioParticular)
                    .addComponent(atualizaRadioPlanodeSaude))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout atualizarPacienteLayout = new javax.swing.GroupLayout(atualizarPaciente);
        atualizarPaciente.setLayout(atualizarPacienteLayout);
        atualizarPacienteLayout.setHorizontalGroup(
            atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, atualizarPacienteLayout.createSequentialGroup()
                        .addComponent(painelSelecionarPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(356, 356, 356))
                    .addGroup(atualizarPacienteLayout.createSequentialGroup()
                        .addGroup(atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(painelAtualizaConvenio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelAtualizaRua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelAtualizaCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelAtualizaNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atualizarPacienteLayout.createSequentialGroup()
                                .addComponent(painelAtualizaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(atualizarPacienteLayout.createSequentialGroup()
                                .addGroup(atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(painelAtualizaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(painelAtualizaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );
        atualizarPacienteLayout.setVerticalGroup(
            atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSelecionarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelAtualizaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelAtualizaTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelAtualizaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelAtualizaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(atualizarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelAtualizaRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelAtualizaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelAtualizaConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        cardOpcoesSecretaria.add(atualizarPaciente, "atualizarPaciente");

        removerPaciente.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout removerPacienteLayout = new javax.swing.GroupLayout(removerPaciente);
        removerPaciente.setLayout(removerPacienteLayout);
        removerPacienteLayout.setHorizontalGroup(
            removerPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        removerPacienteLayout.setVerticalGroup(
            removerPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        cardOpcoesSecretaria.add(removerPaciente, "removerPaciente");

        telaDefault.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout telaDefaultLayout = new javax.swing.GroupLayout(telaDefault);
        telaDefault.setLayout(telaDefaultLayout);
        telaDefaultLayout.setHorizontalGroup(
            telaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        telaDefaultLayout.setVerticalGroup(
            telaDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        cardOpcoesSecretaria.add(telaDefault, "telaDefault");

        cadastrarPaciente.setBackground(new java.awt.Color(51, 51, 51));

        painelCidade.setBackground(new java.awt.Color(51, 51, 51));

        cidadeField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Cidade");

        javax.swing.GroupLayout painelCidadeLayout = new javax.swing.GroupLayout(painelCidade);
        painelCidade.setLayout(painelCidadeLayout);
        painelCidadeLayout.setHorizontalGroup(
            painelCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cidadeField)
                    .addGroup(painelCidadeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelCidadeLayout.setVerticalGroup(
            painelCidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBairro.setBackground(new java.awt.Color(51, 51, 51));

        bairroField.setBackground(new java.awt.Color(255, 255, 255));
        bairroField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroFieldActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Bairro");

        javax.swing.GroupLayout painelBairroLayout = new javax.swing.GroupLayout(painelBairro);
        painelBairro.setLayout(painelBairroLayout);
        painelBairroLayout.setHorizontalGroup(
            painelBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBairroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bairroField)
                    .addGroup(painelBairroLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelBairroLayout.setVerticalGroup(
            painelBairroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBairroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bairroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelNome.setBackground(new java.awt.Color(51, 51, 51));

        nomeField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Nome");

        javax.swing.GroupLayout painelNomeLayout = new javax.swing.GroupLayout(painelNome);
        painelNome.setLayout(painelNomeLayout);
        painelNomeLayout.setHorizontalGroup(
            painelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addGroup(painelNomeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelNomeLayout.setVerticalGroup(
            painelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelRua.setBackground(new java.awt.Color(51, 51, 51));

        ruaField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Rua");

        javax.swing.GroupLayout painelRuaLayout = new javax.swing.GroupLayout(painelRua);
        painelRua.setLayout(painelRuaLayout);
        painelRuaLayout.setHorizontalGroup(
            painelRuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRuaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruaField)
                    .addGroup(painelRuaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelRuaLayout.setVerticalGroup(
            painelRuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ruaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelTelefone.setBackground(new java.awt.Color(51, 51, 51));

        telField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Telefone");

        javax.swing.GroupLayout painelTelefoneLayout = new javax.swing.GroupLayout(painelTelefone);
        painelTelefone.setLayout(painelTelefoneLayout);
        painelTelefoneLayout.setHorizontalGroup(
            painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telField)
                    .addGroup(painelTelefoneLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelTelefoneLayout.setVerticalGroup(
            painelTelefoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelefoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelData.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Data de Nascimento");

        dataNascCalendar.setBackground(new java.awt.Color(255, 255, 255));
        dataNascCalendar.setDateFormatString("dd-MM-yyyy");
        dataNascCalendar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout painelDataLayout = new javax.swing.GroupLayout(painelData);
        painelData.setLayout(painelDataLayout);
        painelDataLayout.setHorizontalGroup(
            painelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDataLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(dataNascCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDataLayout.setVerticalGroup(
            painelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNascCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelConvenio.setBackground(new java.awt.Color(51, 51, 51));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Tipo de Convênio");

        radioParticular.setBackground(new java.awt.Color(51, 51, 51));
        grupoConvenio.add(radioParticular);
        radioParticular.setForeground(new java.awt.Color(204, 204, 204));
        radioParticular.setText("Particular");
        radioParticular.setActionCommand("particular");
        radioParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioParticularActionPerformed(evt);
            }
        });

        radioPlanodeSaude.setBackground(new java.awt.Color(51, 51, 51));
        grupoConvenio.add(radioPlanodeSaude);
        radioPlanodeSaude.setForeground(new java.awt.Color(204, 204, 204));
        radioPlanodeSaude.setText("Plano de Saúde");
        radioPlanodeSaude.setActionCommand("plano de saúde");

        javax.swing.GroupLayout painelConvenioLayout = new javax.swing.GroupLayout(painelConvenio);
        painelConvenio.setLayout(painelConvenioLayout);
        painelConvenioLayout.setHorizontalGroup(
            painelConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConvenioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelConvenioLayout.createSequentialGroup()
                        .addComponent(radioParticular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioPlanodeSaude)))
                .addContainerGap())
        );
        painelConvenioLayout.setVerticalGroup(
            painelConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelConvenioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(painelConvenioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioParticular)
                    .addComponent(radioPlanodeSaude))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        painelSalvar.setBackground(new java.awt.Color(51, 51, 51));

        botaoSalvarDados.setBackground(new java.awt.Color(204, 204, 204));
        botaoSalvarDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoSalvarDados.setForeground(new java.awt.Color(51, 51, 51));
        botaoSalvarDados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        botaoSalvarDados.setText("Salvar");
        botaoSalvarDados.setBorder(null);
        botaoSalvarDados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoSalvarDados.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        botaoSalvarDados.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        botaoSalvarDados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        botaoSalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSalvarLayout = new javax.swing.GroupLayout(painelSalvar);
        painelSalvar.setLayout(painelSalvarLayout);
        painelSalvarLayout.setHorizontalGroup(
            painelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSalvarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoSalvarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        painelSalvarLayout.setVerticalGroup(
            painelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSalvarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSalvarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout cadastrarPacienteLayout = new javax.swing.GroupLayout(cadastrarPaciente);
        cadastrarPaciente.setLayout(cadastrarPacienteLayout);
        cadastrarPacienteLayout.setHorizontalGroup(
            cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarPacienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(cadastrarPacienteLayout.createSequentialGroup()
                        .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(painelConvenio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelRua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelCidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filler6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(painelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 77, Short.MAX_VALUE)))
                .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarPacienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarPacienteLayout.createSequentialGroup()
                                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addComponent(painelSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(painelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(cadastrarPacienteLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        cadastrarPacienteLayout.setVerticalGroup(
            cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastrarPacienteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastrarPacienteLayout.createSequentialGroup()
                        .addGap(0, 169, Short.MAX_VALUE)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cadastrarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cadastrarPacienteLayout.createSequentialGroup()
                                .addComponent(painelSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastrarPacienteLayout.createSequentialGroup()
                                .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)))
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cadastrarPacienteLayout.createSequentialGroup()
                        .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        cardOpcoesSecretaria.add(cadastrarPaciente, "cadastrarPaciente");

        jSplitPane2.setRightComponent(cardOpcoesSecretaria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarMainvoltarMenuPrincipal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarMainvoltarMenuPrincipal
        // TODO add your handling code here:
        this.setVisible(false);
        new trabalho2.Trabalho2().show();
    }//GEN-LAST:event_botaoVoltarMainvoltarMenuPrincipal

    private void botaoRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatorioActionPerformed
    }//GEN-LAST:event_botaoRelatorioActionPerformed

    private void botaoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPacienteActionPerformed
        // TODO add your handling code here:
        menu.show(cardMenu, "menuGerenciarPaciente");
    }//GEN-LAST:event_botaoPacienteActionPerformed

    private void botaoVoltarSecvoltarMenuPrincipal(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarSecvoltarMenuPrincipal
        // TODO add your handling code here:
        limparCampos(getContentPane());
        menu.show(cardMenu, "menuSecretaria");
        opcoesSec.show(cardOpcoesSecretaria, "telaDefault");
                
    }//GEN-LAST:event_botaoVoltarSecvoltarMenuPrincipal

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        opcoesSec.show(cardOpcoesSecretaria, "atualizarPaciente");
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        opcoesSec.show(cardOpcoesSecretaria, "cadastrarPaciente");
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        opcoesSec.show(cardOpcoesSecretaria, "removerPaciente");
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void botaoSalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarDadosActionPerformed
        // TODO add your handling code here:
        Calendar dataSelecionada = dataNascCalendar.getCalendar();
        Secretaria sec = new Secretaria();
        ArrayList dadosInformados = new ArrayList();        

        dadosInformados.add(nomeField.getText());
        dadosInformados.add(telField.getText());
        dadosInformados.add(bairroField.getText());
        dadosInformados.add(cidadeField.getText());
        dadosInformados.add(ruaField.getText());
        dadosInformados.add(grupoConvenio.getSelection().getActionCommand());
        dadosInformados.add(LocalDate.of(dataSelecionada.get(Calendar.YEAR),
                (dataSelecionada.get(Calendar.MONTH)+1),
                dataSelecionada.get(Calendar.DAY_OF_MONTH)));
        
        sec.cadastrarPaciente(dadosInformados);
        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");


        limparCampos(getContentPane());
        //System.out.println(evt);
        
    }//GEN-LAST:event_botaoSalvarDadosActionPerformed

    public Component limparCampos(Component painel){
        
        if (painel instanceof JTextField) {
            JTextField ctrl = (JTextField) painel;
            ctrl.setText("");
        }
        
        if(painel instanceof JSplitPane){
            for (Component entrarSplit : ((JSplitPane) painel).getComponents()) {
                limparCampos(entrarSplit);
            }
        }
        
        if (painel instanceof JPanel){
            for (Component entrarPanel : ((JPanel) painel).getComponents()) {
                limparCampos(entrarPanel);
            }
        }
        grupoConvenio.clearSelection();
        return painel;
    }
    
    private void radioParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioParticularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioParticularActionPerformed

    private void bairroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroFieldActionPerformed

    private void atualizaBairroFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaBairroFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizaBairroFieldActionPerformed

    private void atualizaRadioParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizaRadioParticularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_atualizaRadioParticularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UISecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UISecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UISecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UISecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UISecretaria().setVisible(true);
                
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField atualizaBairroField;
    private javax.swing.JTextField atualizaCidadeField;
    private com.toedter.calendar.JDateChooser atualizaDataNascCalendar;
    private javax.swing.JTextField atualizaNomeField;
    private javax.swing.JRadioButton atualizaRadioParticular;
    private javax.swing.JRadioButton atualizaRadioPlanodeSaude;
    private javax.swing.JTextField atualizaRuaField;
    private javax.swing.JTextField atualizaTelField;
    private javax.swing.JPanel atualizarPaciente;
    private javax.swing.JTextField bairroField;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoConsulta;
    private javax.swing.JButton botaoPaciente;
    private javax.swing.JButton botaoRelatorio;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoSalvarDados;
    private javax.swing.JButton botaoVoltarMain;
    private javax.swing.JButton botaoVoltarSec;
    private javax.swing.JPanel cadastrarPaciente;
    private javax.swing.JPanel cardMenu;
    private javax.swing.JPanel cardOpcoesSecretaria;
    private javax.swing.JTextField cidadeField;
    private com.toedter.calendar.JDateChooser dataNascCalendar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.ButtonGroup grupoConvenio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel menuGerenciarPaciente;
    private javax.swing.JPanel menuSecretaria;
    private javax.swing.JTextField nomeField;
    private javax.swing.JComboBox<String> pacientesBox;
    private javax.swing.JPanel painelAtualizaBairro;
    private javax.swing.JPanel painelAtualizaCidade;
    private javax.swing.JPanel painelAtualizaConvenio;
    private javax.swing.JPanel painelAtualizaData;
    private javax.swing.JPanel painelAtualizaNome;
    private javax.swing.JPanel painelAtualizaRua;
    private javax.swing.JPanel painelAtualizaTelefone;
    private javax.swing.JPanel painelBairro;
    private javax.swing.JPanel painelCidade;
    private javax.swing.JPanel painelConvenio;
    private javax.swing.JPanel painelData;
    private javax.swing.JPanel painelNome;
    private javax.swing.JPanel painelRua;
    private javax.swing.JPanel painelSalvar;
    private javax.swing.JPanel painelSelecionarPaciente;
    private javax.swing.JPanel painelTelefone;
    private javax.swing.JRadioButton radioParticular;
    private javax.swing.JRadioButton radioPlanodeSaude;
    private javax.swing.JPanel removerPaciente;
    private javax.swing.JTextField ruaField;
    private javax.swing.JTextField telField;
    private javax.swing.JPanel telaDefault;
    // End of variables declaration//GEN-END:variables
}
