/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho2;

import POJO.Consulta;
import POJO.DadosAdicionais;
import POJO.Paciente;
import POJO.Prontuario;
import java.util.ArrayList;
import sistema.Secretaria;
import telas.UISecretaria;
import usuario.TipoUsuario
;

/**
 *
 * @author aleix
 */
public class Trabalho2 extends javax.swing.JFrame {

    /**
     * Creates new form Trabalho2POO
     */
    ArrayList<Paciente> pacientes = new ArrayList();
    ArrayList<Consulta> consultas = new ArrayList();
    ArrayList<Prontuario> prontuario = new ArrayList();
    ArrayList dados = new ArrayList();
    ArrayList<DadosAdicionais> dadosAdicionais = new ArrayList();

    //Medico medico = new Medico(pacientes,consultas, dadosAdicionais, prontuario);
    Secretaria secretaria = new Secretaria(pacientes, consultas);
    //GerenciadorMensagem gerenciador = new GerenciadorMensagem(pacientes, consultas);

    TipoUsuario tipoUsuario = new TipoUsuario();
    public Trabalho2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioMens = new javax.swing.JButton();
        usuarioSec = new javax.swing.JButton();
        usuarioMed = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuarioMens.setBackground(new java.awt.Color(204, 204, 204));
        usuarioMens.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usuarioMens.setForeground(new java.awt.Color(51, 51, 51));
        usuarioMens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        usuarioMens.setText("Gerenciador de Mensagem");
        usuarioMens.setBorder(null);
        usuarioMens.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioMens.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        usuarioMens.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        usuarioMens.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N

        usuarioSec.setBackground(new java.awt.Color(204, 204, 204));
        usuarioSec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usuarioSec.setForeground(new java.awt.Color(51, 51, 51));
        usuarioSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        usuarioSec.setText("Secretaria");
        usuarioSec.setBorder(null);
        usuarioSec.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioSec.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        usuarioSec.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        usuarioSec.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N
        usuarioSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioSecActionPerformed(evt);
            }
        });

        usuarioMed.setBackground(new java.awt.Color(204, 204, 204));
        usuarioMed.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usuarioMed.setForeground(new java.awt.Color(51, 51, 51));
        usuarioMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/default.png"))); // NOI18N
        usuarioMed.setText("Medico");
        usuarioMed.setBorder(null);
        usuarioMed.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usuarioMed.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/pressed.png"))); // NOI18N
        usuarioMed.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/hover.png"))); // NOI18N
        usuarioMed.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/selected.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(usuarioSec, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuarioMed, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuarioMens, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioSec, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(usuarioMed, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(usuarioMens, javax.swing.GroupLayout.PREFERRED_SIZE, 44, Short.MAX_VALUE))
                .addGap(260, 260, 260))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioSecActionPerformed

        new UISecretaria().setVisible(true);
        this.dispose();
        tipoUsuario.setUsuario(secretaria);
        
    }//GEN-LAST:event_usuarioSecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabalho2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabalho2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabalho2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabalho2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabalho2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton usuarioMed;
    private javax.swing.JButton usuarioMens;
    private javax.swing.JButton usuarioSec;
    // End of variables declaration//GEN-END:variables
}
